#ifndef NA63_SIMULATION_TRACK_H
#define NA63_SIMULATION_TRACK_H

namespace na63 {

  /**
   * Track data struct, should always be aligned to 32 bytes to take advantage
   * of memory bursts.
   * particle_id should be specified before propagation, while
   * particle_index is generated by the propagation engine.
   */
  typedef struct {
    int particle_id;    // According to Monte Carlo Particle Numbering Scheme
    int particle_index; // Index into Particle array, managed dynamically
    float r[3];
    float p[3];
    // Align to 32 bytes
    // char padding[0]; // Currently aligned
  } Track;

}

#endif /* NA63_SIMULATION_TRACK_H */